%% Example of pipeline with default parameters
%   - Notes:
%   Refer to wiki page:
%   https://wiki.aalto.fi/pages/viewpage.action?pageId=92445275 for
%   detailed documentation
%	Last edit: AT 17-10-2019


%%
% Copy this to your folder, specify subject folders with correct file names
%
% Subject folders should contain:
% -epi.nii (functional data)
% -bet.nii (brain-extracted anatomical image)
% -if drifter was used, also .acq file with respiration and heartbeat.
%%
clear all
clear cfg; % Running also "clearn all" is good practice to start from an empty and clean workspace

addpath(genpath('/m/nbe/scratch/braindata/shared/toolboxes/bramila/bramila'));
addpath('/m/nbe/scratch/braindata/shared/toolboxes/NIFTI');


%% List subject input folders
subjects = {
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10274'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60033'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10882'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-11098'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10523'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50052'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10159'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10471'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70040'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-11068'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70020'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70004'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10361'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50058'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10629'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50016'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60074'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50036'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50025'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50023'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10249'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10893'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70076'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10339'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10271'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10321'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10273'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10206'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70007'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60049'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-11104'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10680'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10724'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50005'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60001'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70033'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50076'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60073'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60060'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10949'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-11106'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-11062'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60048'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10227'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60066'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70074'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60020'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50032'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-11105'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10877'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60012'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10871'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50014'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50007'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60076'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60070'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10762'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60087'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10527'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10376'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50022'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70070'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70079'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-11044'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10525'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10707'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10269'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-11061'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50027'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70072'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10557'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10975'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70021'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60084'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70046'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70081'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10785'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70068'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50081'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60046'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10788'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50083'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60008'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-11019'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60078'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50067'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60030'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50006'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50085'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50035'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60017'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10292'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10987'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10708'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10779'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60077'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10998'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10692'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70080'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70049'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70001'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10855'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60052'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70073'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10448'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50043'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50020'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50073'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70015'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60014'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60055'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50054'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-11142'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60051'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60062'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60021'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60037'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50004'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50048'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50064'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10696'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60016'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-11149'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70086'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50008'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10228'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70026'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60022'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60045'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70022'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60053'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70083'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70057'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-11143'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10304'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60038'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50066'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60072'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60015'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-11090'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-11067'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10235'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10638'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10678'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10492'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10325'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50055'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50015'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50051'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60080'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10440'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10940'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60043'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50077'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10356'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10524'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60056'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60065'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10388'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10189'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10280'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10719'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10624'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10171'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10631'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-11066'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10570'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60057'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60079'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10565'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50047'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50075'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50010'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50021'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70060'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50053'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-11030'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10912'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70061'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10674'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60042'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10746'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50069'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10345'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50056'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70034'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60006'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70069'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10891'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-11156'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10704'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-11097'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10438'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60011'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10672'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60068'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10478'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70065'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50061'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50013'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50029'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10668'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60036'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-11122'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10347'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10340'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10963'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10968'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70052'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70010'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50080'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50060'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10316'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10329'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10429'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70051'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10977'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50033'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50038'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10575'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10958'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10217'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10460'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60028'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-11088'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10455'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10487'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10506'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10530'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-11050'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70055'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50034'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10517'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50059'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10697'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60010'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-11052'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-11077'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70058'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10686'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10365'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-11112'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70029'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-11128'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70075'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50050'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70037'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-11131'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10844'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60089'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10934'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10377'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70048'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-11059'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70017'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-70077'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10225'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-60005'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-11108'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-50049'
'/m/cs/scratch/networks/data/UCLA_openneuro/Preprocessed/sub-10290'
};

%% List subjects output folders
subjects_out = {
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10274'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60033'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10882'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-11098'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10523'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50052'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10159'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10471'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70040'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-11068'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70020'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70004'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10361'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50058'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10629'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50016'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60074'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50036'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50025'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50023'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10249'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10893'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70076'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10339'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10271'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10321'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10273'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10206'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70007'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60049'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-11104'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10680'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10724'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50005'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60001'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70033'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50076'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60073'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60060'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10949'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-11106'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-11062'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60048'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10227'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60066'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70074'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60020'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50032'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-11105'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10877'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60012'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10871'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50014'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50007'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60076'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60070'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10762'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60087'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10527'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10376'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50022'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70070'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70079'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-11044'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10525'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10707'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10269'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-11061'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50027'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70072'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10557'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10975'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70021'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60084'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70046'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70081'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10785'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70068'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50081'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60046'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10788'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50083'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60008'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-11019'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60078'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50067'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60030'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50006'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50085'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50035'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60017'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10292'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10987'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10708'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10779'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60077'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10998'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10692'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70080'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70049'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70001'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10855'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60052'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70073'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10448'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50043'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50020'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50073'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70015'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60014'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60055'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50054'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-11142'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60051'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60062'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60021'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60037'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50004'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50048'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50064'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10696'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60016'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-11149'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70086'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50008'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10228'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70026'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60022'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60045'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70022'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60053'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70083'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70057'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-11143'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10304'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60038'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50066'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60072'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60015'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-11090'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-11067'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10235'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10638'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10678'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10492'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10325'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50055'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50015'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50051'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60080'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10440'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10940'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60043'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50077'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10356'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10524'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60056'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60065'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10388'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10189'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10280'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10719'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10624'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10171'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10631'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-11066'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10570'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60057'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60079'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10565'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50047'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50075'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50010'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50021'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70060'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50053'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-11030'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10912'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70061'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10674'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60042'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10746'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50069'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10345'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50056'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70034'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60006'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70069'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10891'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-11156'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10704'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-11097'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10438'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60011'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10672'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60068'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10478'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70065'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50061'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50013'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50029'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10668'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60036'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-11122'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10347'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10340'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10963'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10968'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70052'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70010'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50080'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50060'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10316'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10329'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10429'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70051'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10977'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50033'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50038'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10575'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10958'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10217'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10460'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60028'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-11088'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10455'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10487'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10506'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10530'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-11050'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70055'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50034'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10517'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50059'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10697'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60010'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-11052'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-11077'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70058'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10686'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10365'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-11112'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70029'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-11128'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70075'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50050'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70037'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-11131'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10844'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60089'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10934'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10377'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70048'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-11059'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70017'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-70077'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10225'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-60005'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-11108'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-50049'
'/m/cs/scratch/networks/data/UCLA_openneuro/Brainnetome_0mm/sub-10290'
};
% subjects_out = subjects; % in case you want to store everything under the same original folder


%% General settings
cfg.overwrite = 1; % set to one if you are re-running preprocessing and you want to overwrite existing files
cfg.bramilapath = '/m/nbe/scratch/braindata/shared/toolboxes/bramila/bramila'; % bramila toolbox path
cfg.StdTemplate='/m/nbe/scratch/braindata/shared/HarvardOxford/MNI152_T1_2mm_brain.nii'; % 2mm MNI template from FSL
cfg.TR = 2; % TR from scanning protocol, used in bramila
cfg.rmvframes = 5; % How many volumes to remove in the beginning (sync trial)

%% temporal filtering
cfg.do_temporal_filtering = 1;
cfg.filtertype = 'butter'; % allowed are butter, fir, fslhp. Use fslhp if you are not doing functional connectivity. Use butter to do like in Power 2014

%% Smoothing
cfg.do_spatial_smooth = 0;
cfg.smooth_FWHM = 0; % used in susan smoothing
cfg.smooth_method = 'FSLgauss'; % 'SPM', 'AFNI', 'FSL' or 'none'

%% slice number parameters, use only one, either slicenum or sliceseq
%cfg.slicenum = 33; % slice count: used in slicetimer, in Siemens scanner odd number of slices starts from 1, even starts from 2
cfg.sliceseq = [2:2:34 1:2:34]; % prespecified slice acquisition sequence

%% Drifter settings
cfg.drifter = 0; % 1 if you have biopac measurements
cfg.driftermode = 0; % 0 = BOLD estimate only, 1 = BOLD+residual added back

%% Biopac settings, these are setup according to the template that Dima and Heini use
% Which channels were active 1 - active, 0 - not active
biopacfile.CH1=1; %usually breath data from belt
biopacfile.CH2=0; %usually ECG
biopacfile.CH3=0; %usually GSR
biopacfile.CH4=1; %usually heart rate from pulse oxymeter_left
biopacfile.CH5=0; %usually heart rate from pulse oxymeter_right
biopacfile.CH35=1; %usually MRI scan off/on information
% sampling interval of physiodata and fMRI
biopacfile.dt=0.001; % in seconds/sample
biopacfile.controlplot=1 ;% plots all data and save as filename.fig
biopacfile.breath=0.01;%new sampling interval for breath it should not be higher than 2.4( for 25 inhales/min)
biopacfile.HR=0.01; %new sampling interval for heart rate, should not be higher than 0.75(for 80 bpm)
% set the range for frequencies in signals in bpm (try to keep those as narrow as posible)
biopacfile.freqBreath=10:25; % in breaths per min
biopacfile.freqHR=40:90; % in beats per minutes
biopacfile.filter=1; % bandpass filter for reference data 1 - active, 0 - not active
cfg.biopacfile = biopacfile;

%% Bramila parameters for optimized cleaning of artefacts
% OPTIONAL parameters (otherwise use defaults as marked here in the example)
% Modify only if needed (see "bramila_checkparameters.m" for defaults)
% cfg.motion_reg_type = 'friston'; % motion regression type
% cfg.voxelsize=[2,2,2];        % voxelsize
% cfg.mask = [];                % initial EPI mask
% cfg.tissue_derivatives = 0;   % tissue regressor derivative order
% cfg.min_tissue_var_expl = 75; % minimum variance percentage for tissue PCA regressors
% cfg.max_tissue_pca_count = 7; % upper limit for tissue PCA regressors
 cfg.remove_global = 1;        % remove global signal
% cfg.mot_derivatives = 1;  % motion regressor derivatives
% cfg.white_mask_th = 0.90; % probability threshold for white matter tissue
% cfg.csf_mask_th = 0.90;   % probability threshold for ventricle tissue
 cfg.detrend_type='Savitzky-Golay';   % detrending type
 cfg.filter_type = 'butter';   % temporal filter type
% cfg.filter_limits = [0,0.01,0.08,0.09];   % filter limits in Hz
cfg.write = 1;    % write all intermediate EPI's
% cfg.save_path = '/m/nbe/scratch/braindata/kauttoj2/code/bramila_git/bramila/out'; % custom save path for bramila motion cleaning results


%% Running preprocessing. Do not modify the code below
cfg = bramila_parhandle(cfg,subjects,subjects_out); % reslices the cfg so that it can be used in parfor loop
if ~strcmp(cfg{1}.gridtype,'slurm')
    parfor i = 1:length(subjects)
        bramila_preprocessor(cfg{i});
    end
else
    for i = 1:length(subjects)
        bramila_slurmprepro(cfg{i});
    end
end
